
name: "Release"

on:
  release:
    types:
      - "published" 

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: Upload release assets
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: dist/*
